name: Windows Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest
    env:
      APP_VERSION: ${{ github.ref_name }}   # tag like v0.1.0
    steps:
      - uses: actions/checkout@v4

      # Install Qt 6 (Widgets/Network)
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: true

      # Build daemon (miqrod)
      - name: Configure core
        run: cmake -S . -B build -A x64
      - name: Build core
        run: cmake --build build --config Release

      # Build GUI
      - name: Configure GUI
        run: cmake -S gui/miqro-gui -B build-gui -DCMAKE_PREFIX_PATH="$env:Qt6_DIR"
      - name: Build GUI
        run: cmake --build build-gui --config Release

      # Install Inno Setup via Chocolatey
      - name: Install Inno Setup
        run: choco install innosetup -y

      # Package installer (windeployqt + ISCC)
      - name: Package installer
        run: |
          powershell -ExecutionPolicy Bypass -File installers\package-win.ps1 `
            -QtBin "$env:Qt6_DIR\..\..\bin" `
            -GuiExe ".\build-gui\Release\miqro-gui.exe" `
            -DaemonExe ".\build\Release\miqrod.exe" `
            -OpenSslDir "C:\Qt\Tools\OpenSSL\Win_x64\bin"
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: miqrochain-setup-${{ env.APP_VERSION }}
          path: dist\installer\*.exe

      # (Optional) Attach to GitHub Release
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/installer/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
